import { fetchCandidates } from "./fetch";
import { scoreCandidates, generateDigest, generateLinkedInPost, generateTweets } from "./generate";
import { getProfile, getFeedbackForProfile, getWritingSample, saveOutput, saveProfile } from "./db";
import { DigestRun } from "./types";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function formatOutputMarkdown(
  profileName: string,
  topic: string,
  format: string,
  date: string,
  sourcesUsed: number,
  digest: string,
  linkedinPost: string,
  tweets: string[]
): string {
  return `# ${profileName} — ${date}

**Topic:** ${topic}
**Format:** ${format}
**Sources used:** ${sourcesUsed} sources

---

## Digest

${digest}

---

## LinkedIn Post

${linkedinPost}

---

## Tweets

1. ${tweets[0] ?? ""}
2. ${tweets[1] ?? ""}
3. ${tweets[2] ?? ""}

---

*Generated by Newsletter Builder*
`;
}

export async function runPipeline(profileId: string): Promise<DigestRun> {
  const profile = getProfile(profileId);
  if (!profile) throw new Error(`Profile ${profileId} not found`);

  const feedback = getFeedbackForProfile(profileId);

  // Step 1: Fetch candidates
  const candidates = await fetchCandidates(profile.sources, profile.topic);

  // Step 2: Score + filter
  const targetCount = profile.format === "flash" ? 5 : profile.format === "brief" ? 3 : 5;
  const scored = await scoreCandidates(candidates, profile.topic, feedback, targetCount);

  // Step 3: Generate digest
  const digest = await generateDigest(scored, profile.format, profile.topic);

  // Steps 4 & 5: Generate social posts
  const writingSample = getWritingSample(profileId);
  const topStory = scored[0];
  const linkedinPost = topStory
    ? await generateLinkedInPost(topStory, profile.topic, writingSample, profile.linkedinStyle)
    : "No stories available.";
  const tweets = topStory
    ? await generateTweets(topStory, profile.topic, null, profile.tweetStyle)
    : ["No stories available."];

  // Step 6: Save output
  const date = new Date().toISOString().split("T")[0];
  const slug = slugify(profile.name);
  const outputContent = formatOutputMarkdown(
    profile.name,
    profile.topic,
    profile.format,
    date,
    profile.sources.length,
    digest,
    linkedinPost,
    tweets
  );
  saveOutput(slug, date, outputContent);

  // Update lastRunAt
  profile.lastRunAt = new Date().toISOString();
  saveProfile(profile);

  return {
    profileId,
    date,
    digest,
    linkedinPost,
    tweets,
    sourcesUsed: profile.sources.length,
    stories: scored,
  };
}
